spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: 111
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
    show-sql: true
    open-in-view: true


logging:
  level:
    root: info
    com.huang: debug
  file: log/blog-dev.log


